/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Planet.glb -o src/components/Planet.jsx -k -r public 
*/

import React from "react"
import {useGLTF} from "@react-three/drei"

export function Planet(props) {
  const {nodes, materials} = useGLTF("/models/Planet.glb")
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Planet_7"
        geometry={nodes.Planet_7.geometry}
        material={materials.Atlas}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload("/models/Planet.glb")
